services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: notepad_final
    ports:
      - "3306:3306"
    volumes:
      # Chạy file init.sql để tạo bảng ngay khi khởi động
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root_password
      DB_NAME: notepad_final
      # Các biến Email bạn nên để trong file .env ở gốc
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      - db

volumes:
  mysql_data: